#!/bin/bash
#
# Copyright (c) 2009-2012 NITLab, University of Thessaly, CERTH, Greece
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Syntax: create_slice [slice_name] [xmpp_server]
#
# == Description
#
# This script creates the new slice account.
# When a registered user requests a slice, we execute manually this script to create it.
#

/usr/sbin/useradd -m -d /home/$1 -s /bin/bash $1

# Add user to the users group so sudo commands  work
/usr/sbin/usermod -G users $1
# Create user with empty pass
mkdir /home/$1/.ssh
/bin/chown -R $1 /home/$1/.ssh
touch /home/$1/.ssh/authorized_keys

# Create OMF slice
/usr/sbin/omf_create_psnode-5.4 $2 mkslice $1

# Insert slice in Scheduler's database and return the id
id=`ruby /root/add_to_AM_config.rb $1`
/etc/init.d/omf-aggmgr-5.4 restart

# Create Flowvisor slice
sshpass -p 'fv_password' ssh -o StrictHostKeyChecking=no flowvisor@flowvisor "echo 'slice_password' | /usr/bin/fvctl-xml --passwd-file=/home/flowvisor/.fvp createSlice $1 tcp:127.0.0.1:9$id $1@mail.com"