#!/bin/bash
#
# Copyright (c) 2009-2012 NITLab, University of Thessaly, CERTH, Greece
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Syntax: disable_node [uid] [node_ip] [xmpp_server]
#
# == Description
#
# This script is used to remove firewall rules added by the scheduler.
# Called automatically by the scheduler. Please do not call it manually.
#

#------------------- OMF Scheduler -----------------

map=(00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50)

# for OMF 5.3
#/usr/sbin/omf_create_psnode-5.3 $3 rmnode /OMF/$1/resources/omf.nitos.node0${map[$2]}
# for OMF 5.4
/usr/sbin/omf_create_psnode-5.4 $3 rmnode /OMF_5.4/$1/resources/omf.nitos.node0${map[$2]}

#-------------------- OpenFlow Slicing --------------------#
# The configuration below works for 1 OpenFlow switch.     #
# In case of more OpenFlow switches, like in NITOS, please #
# contact NITOS administrators for further advice on       #
# the configuration of the OpenFlow slicing...             #

#------------------- Remove FlowSpace ---------------------#
fvctl___port=(0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44)

FLOW_SPACE_IDS=$(sshpass -p 'fv_password' ssh -o StrictHostKeyChecking=no flowvisor@flowvisor "/usr/bin/fvctl-xml --passwd-file=/home/flowvisor/.fvp listFlowSpace | grep 'dpid=\[00:00:00:00:00:00:00:0${datapath_id}\]' |     grep 'in_port=${fvctl___port[$2]}' | grep 'Slice:$1' | cut -d, -f4 | cut -d[ -f2 | cut -d] -f1")

#------------------- Switch Off the Node-------------
#curl http://10.1.0.$2/off

#------------------- Remove access to Control Network -----------------
iptables -D OUTPUT -d 10.0.1.$2 -m owner --uid-owner $1 -j ACCEPT
iptables-save > /etc/iptables/rules.v4
