#!/bin/bash
#
# Copyright (c) 2009-2012 NITLab, University of Thessaly, CERTH, Greece
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Syntax: enable_node [uid] [node_ip] [xmpp_server]
#
# == Description
#
# This script is used to enable the specified node for the specified user.
# Called automatically by the scheduler. Please do not call it manually.
#

#------------------- OMF Scheduler -----------------

map=(00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50)

/usr/sbin/omf_create_psnode-5.4 $3 sliceadd $1 omf.nitos.node0${map[$2]}

#------------- Give access to Control Network -----------------
#iptables -A OUTPUT -p all -d 10.0.0.$2 -m owner --uid-owner $1 -j ACCEPT
iptables -D OUTPUT -o eth1 -j REJECT
iptables -A OUTPUT -d 10.0.1.$2 -m owner --uid-owner $1 -j ACCEPT
iptables -A OUTPUT -o eth1 -j REJECT
